from __future__ import annotations

THEME_PRIMARY = "4472C4"

THEME_BACKGROUND = "FFFFFF"
THEME_CARD = "F8F9FA"
THEME_CHART_PRIMARY = "63C384"

THEME_SUCCESS = "C6EFCE"
THEME_WARNING = "FFF2CC"
THEME_CRITICAL = "F4CCCC"

THEME_DIFF_GREEN = "C6EFCE"
THEME_DIFF_YELLOW = "FFEB9C"
THEME_DIFF_RED = "FFC7CE"

THEME_TEXT_DARK = "1F1F1F"
THEME_TEXT = "404040"
THEME_TEXT_LIGHT = "666666"
THEME_TITLE = "1F4E78"
THEME_WHITE = "FFFFFF"

THEME_HEADER = "F2F2F2"

THEME_SUMMARY = "F3F6FA"

THEME_BORDER = "000000"

THEME_POSITIVE = "006100"
THEME_NEGATIVE = "C00000"

#
# Dashboard Charts
#

CHART_WIDTH = 10
CHART_HEIGHT = 8

PIE_CHART_POSITION = "H3"
BAR_CHART_POSITION = "T3"
