DATE = "FİŞ TARİHİ"
JOURNAL_NO = "YEVMİYE NO"
VOUCHER_NO = "FİŞ NO"
TIF_NO = "TAŞINIR İŞLEM FİŞ NO"
VOUCHER_TYPE = "FİŞ TİP"
DESCRIPTION = "DSC"
INVOICE_NO = "ÖDEMEYE ESAS BELGE(FATURA NO)"
TAX_NO = "VERGİ NO"
SUPPLIER = "TC/VERGİ NO ADI"
DEBIT = "BORÇ"
CREDIT = "ALACAK"

REQUIRED_COLUMNS = [
    DATE,
    JOURNAL_NO,
    VOUCHER_NO,
    TIF_NO,
    VOUCHER_TYPE,
    DESCRIPTION,
    INVOICE_NO,
    TAX_NO,
    SUPPLIER,
    DEBIT,
    CREDIT,
]